[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.69"
bytemuck = "1.13.0"
quote = "1.0.23"
syn = "1.0.107"
thiserror = "1.0.38"
uuid = "1.3.0"
wrapmuck = { version = "0.2.0", path = "./crates/wrapmuck" }
