[package]
name = "daicon"
version = "0.4.0"
edition = "2021"
description = "Daicon low-level types, for zero-copy reading and writing"
readme = "../../README.md"
repository = "https://github.com/open-mv-sandbox/daicon"
license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
